name: Docker Image CI

on:
  push:
    tags:
      - '*'

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  GITHUB_CONTAINER_REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Login to DockerHub
      run: echo -n "$DOCKER_ACCESS_TOKEN" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin
        
    - name: Login to GitHub Container Registry
      run: echo -n "$GITHUB_TOKEN" | docker login "$GITHUB_CONTAINER_REGISTRY" -u "${{ github.actor }}" --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run publish script
      run: ./bin/publish.sh
